[package]
name = "xp-ch-word-splitter-worker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-derive = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
jieba-rs = "0.7.0"
